### ISSUE TITLE
Requests with dictionaries shows [object Object]

### ISSUE THREAD

**Issue by juharris** [microsoft/ApplicationInsights-Python#118]
I'm logging requests with dictionaries that are a few levels deep and in Application Insights but I cannot see what's after the first level. Instead it just shows `[object Object]`.

Example:
```python
impl = TelemetryClient('my key')
impl.track_request('test', 'url', success=True, properties=dict(a=dict(b=1)))
impl.flush()
```
![image](https://user-images.githubusercontent.com/1594505/43329333-118d0ebc-918e-11e8-9413-4fa0e241e38a.png)

How can I get the inner objects to show properly as dictionaries?

**Comment by juharris** [comment]
Similar to https://github.com/Microsoft/ApplicationInsights-node.js/issues/371

The workaround suggested there with just stringifying is not good because it makes working with the objects where searching not as nice.

**Comment by juharris** [comment]
Thanks for the help!
This is surprising because I didn't see this caveat documented anywhere and it's weird that `tostring` is required.
**Why not just stringify the dict in the library?**

BTW it's `parse_json`.  So for now, here is a complete working example for anyone that stumbles across this:
```python
import json

def convert_for_app_insights(d: dict) -> dict:
    return {k: json.dumps(v, separators=(',', ':')) if isinstance(v, dict) else v
            for (k, v) in d.items()}

impl = TelemetryClient('my key')
properties = dict(a=dict(b=1))
impl.track_request('test', 'url', success=True, properties=convert_for_app_insights(properties))
impl.flush()
```

Querying:
```
requests | where parse_json(tostring(customDimensions['a']))['b'] == 1
```

**Comment by lgodmer** [comment]
I guess the library doesn't stringify because stringifying is dangerous for a few reasons:

1. If the object is cyclic it will throw - yes you can try catch and/or write some logic to detect and remove cycles but it might not yield the result the client is expecting.

2. If the stringified version is too long it will cause the telemetry to be rejected by the server. The client can still pass in a string that is too long and hit the same issue, but I feel if the library is abstracting this, it makes the issue harder to detect and fix.

In my opinion, it is most flexible and consistent to leave it up to the client to figure out how to stringify their own objects.
