### ISSUE TITLE
Benefit from this package without using AzureInsights? (Offline Use within docker-compose?)

### ISSUE THREAD

**Issue by andife** [microsoft/ApplicationInsights-Python#300]
Hi,

I wonder can I already benefit from this package without using AzureInsights? I.e. offline when testing outside of azure. E.g. in docker-compose? Are there tools to easily evaluate and possibly visualize the results offline?

**Comment by jeremydvoss** [comment]
You could add a console exporter for each signal so that the telemetry is outputted directly to you. For instance, to export traces to console, you can call:
configure_azure_monitor()
trace_exporter = ConsoleSpanExporter()
span_processor = BatchSpanProcessor(
    trace_exporter,
)
get_tracer_provider().add_span_processor(span_processor)

**Comment by lzchen** [comment]
@andife 

Is your issue resolved?

**Comment by andife** [comment]
Thanks for asking. The theme is taking a bit of a break right now, which means I honestly haven't gotten around to evaluating it yet, but I hope to very soon.

**Comment by lzchen** [comment]
Will be closing for now. Feel free to open back up if you want to revisit.
