### ISSUE TITLE
AI: Server telemetry channel was not initialized. So persistent storage is turned off. You need to call ServerTelemetryChannel.Initialize(). Currently monitoring will continue but if telemetry cannot be sent it will be dropped.

### ISSUE THREAD

**Issue by emft** [Microsoft/ApplicationInsights-Python#80]
I'm using the vanilla defaults with Django, installed as shown in the docs.  And every half hour, I get this trace in App Insight:
`
AI: Server telemetry channel was not initialized. So persistent storage is turned off. You need to call ServerTelemetryChannel.Initialize(). Currently monitoring will continue but if telemetry cannot be sent it will be dropped.
`

As well, this trace also shows up occasionally:
`
AI: Performance counter is not available in the web app supported list. Counter is \Memory\Available Bytes
`

I've poked around the portal but haven't seen anything that would address this.  Getting these messages makes it seem like something is improperly configured, but like I said, I'm just using the vanilla Django defaults installed per instruction.  Please advise.  Thanks.

**Comment by SergeyKanzhelev** [comment]
First is related to https://github.com/Microsoft/ApplicationInsights-dotnet/issues/756 It is caused by Application Insights Profiler installed on your web site with the Application Insights Extension. This message should not affect any data collection.

Second message is from the .NET process being monitoring by the same Application Insights Extension. Every windows-based Web App is running IIS. And occasionally .NET may be loaded when your site is pinged with `/Default.aspx` route or something.

You can safely ignore both or uninstall Azure Web App extension if you want to get rid of those.

**Comment by SergeyKanzhelev** [comment]
Please re-open if you have more questions.
